# @package _global_

defaults:
  # /home/tsaisplus/mrs_llm/myproject/habitat-lab/habitat-lab/habitat/config/benchmark/nav/pointnav/pointnav_base.yaml
  - pointnav_base
  # /habitat-lab/habitat-lab/habitat/config/habitat/dataset/pointnav/habitat_test.yaml
  - /habitat/dataset/pointnav: habitat_test
  - _self_

habitat:
  environment:
    max_episode_steps: 500
  simulator:
    agents:
      main_agent:
        sim_sensors:
          rgb_sensor:
            width: 256
            height: 256
          depth_sensor:
            width: 256
            height: 256
