# @package habitat.simulator.agents.rgbd_agent

defaults:
  - /habitat/simulator/sim_sensors@sim_sensors.rgb_sensor: rgb_sensor
  - /habitat/simulator/sim_sensors@sim_sensors.depth_sensor: depth_sensor
    # refer to /home/tsaisplus/mrs_llm/habitat-lab/habitat-lab/habitat/config/default_structured_configs.py
