# @package _global_

defaults:
  - /habitat: habitat_config_base
  - /habitat/task: objectnav
  - /habitat/simulator/sensor_setups@habitat.simulator.agents.main_agent: rgbd_agent
  - /habitat/dataset/objectnav: mp3d
  - _self_

habitat:
  task:
    measurements:
      success:
        success_distance: 0.1
    success_reward: 2.5
    slack_reward: -1e-3
  dataset:
    type: ObjectNav-v2
    split: "select"
    train_eps: 1
    data_path: "data/datasets/objectnav/objectnav_mp3d_70k/{split}/{split}.json.gz"
    scenes_dir: "data/scene_datasets/"
    max_replay_steps: 5000
  environment:
    max_episode_steps: 5000

  simulator:
    action_space_config: 'v1'
    turn_angle: 30
    agents:
      main_agent:
        sim_sensors:
          rgb_sensor:
            width: 640
            height: 480
            hfov: 79
            position: [0, 0.88, 0]
          depth_sensor:
            width: 640
            height: 480
            hfov: 79
            min_depth: 0.5
            max_depth: 5.0
            position: [0, 0.88, 0]
        height: 0.88
        radius: 0.18
    habitat_sim_v0:
      gpu_device_id: 0
      allow_sliding: False
